global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - "20.106.202.149:9093"

rule_files:
  - "alert_rules.yml"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["20.106.202.149:9090"]

  - job_name: "node_exporter"
    static_configs:
      - targets: ["20.106.202.149:9100"]

  - job_name: "alertmanager"
    static_configs:
      - targets: ["20.106.202.149:9093"]